In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

import numpy as np

import warnings
warnings.filterwarnings('ignore')


import pylab as plt
import seaborn as sns


%matplotlib inline

In [2]:
import os

In [4]:
import glob

# Obtener la lista de todos los archivos CSV en el directorio actual
archivos_csv = glob.glob('data/carmen/*.csv')

# Crear una lista vacía para almacenar los datos de los archivos CSV
datos_csv = []

# Leer cada archivo CSV y agregar sus datos a la lista
for archivo in archivos_csv:
    datos = pd.read_csv(archivo)
    datos_csv.append(datos)

# Concatenar los datos de todos los archivos en un solo DataFrame
datos_combinados = pd.concat(datos_csv)

# Guardar los datos combinados en un nuevo archivo CSV
datos_combinados.to_csv('carmen.csv', index=False)

In [14]:
carmen = pd.read_csv('carmen.csv')

In [15]:
carmen

,producto,marca,formato,cantidad,precio,supermercado
0,Café molido natural,Hacendado,Paquete,500 g,"3,65 €",Mercadona
1,Café molido natural,Hacendado,Paquete,250 g,"1,85 €",Mercadona
2,Café molido mezcla fuerte,Hacendado,Paquete,500 g,"3,40 €",Mercadona
3,Café molido mezcla fuerte,Hacendado,Paquete,250 g,"1,75 €",Mercadona
4,Café molido natural fuerte,Hacendado,Paquete,500 g,"3,25 €",Mercadona
...,...,...,...,...,...,...
2210,Toallitas íntimas cuidado diario,Deliplus,Paquete,25 ud.,"1,30 €",Mercadona
2211,Toallitas íntimas cuidado diario,Deliplus,Paquete,12 ud.,"0,85 €",Mercadona
2212,Toallitas íntimas cuidado diario monodosis,Deliplus,Caja,20 sobres,"1,80 €",Mercadona
2213,Gel de higiene íntima,Deliplus,Bote,500 ml,"1,25 €",Mercadona
2214,Gel de higiene íntima hidratante,Deliplus,Bote,500 ml,"2,25 €",Mercadona

In [16]:
carmen.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2215 entries, 0 to 2214
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   producto      2215 non-null   object
 1   marca         2215 non-null   object
 2   formato       2209 non-null   object
 3   cantidad      2215 non-null   object
 4   precio        2215 non-null   object
 5   supermercado  2215 non-null   object
dtypes: object(6)
memory usage: 965.3 KB

In [17]:
carmen.describe(include='all').T

             count unique                   top  freq
producto      2215   1807  Agua mineral natural    24
marca         2215    290              Deliplus   542
formato       2209     38                  Caja   295
cantidad      2215    473                 1 ud.   283
precio        2215    349                2,50 €    66
supermercado  2215      2             Mercadona  1175

In [18]:
carmen.dtypes

producto        object
marca           object
formato         object
cantidad        object
precio          object
supermercado    object
dtype: object

In [31]:
carmen.to_csv('carmen.csv', index=False)

In [5]:
archivos_csv = glob.glob('data/glyeb/*.csv')

# Crear una lista vacía para almacenar los datos de los archivos CSV
datos_csv = []

# Leer cada archivo CSV y agregar sus datos a la lista
for archivo in archivos_csv:
    datos = pd.read_csv(archivo)
    datos_csv.append(datos)

# Concatenar los datos de todos los archivos en un solo DataFrame
datos_combinados = pd.concat(datos_csv)

# Guardar los datos combinados en un nuevo archivo CSV
datos_combinados.to_csv('glyeb.csv', index=False)

In [6]:
glyeb = pd.read_csv('glyeb.csv')

In [7]:
glyeb

,producto,marca,formato,cantidad,precio,supermercado
0,Alubias blancas,Vegecampo de Dia,bolsa,1 Kg,"2,00 €",Dia
1,Alubias pintas,Vegecampo de Dia,bolsa,1 Kg,"2,26 €",Dia
2,Alubia negra,Vegecampo de Dia,bolsa,500 g,"1,20 €",Dia
3,Alubias blancas bajo contenido en sal,Vegecampo de Dia,frasco,400 g,"0,95 €",Dia
4,Alubias rojas cocidas,Vegecampo de Dia,frasco,400 g,"1,05 €",Dia
...,...,...,...,...,...,...
1580,"Natillas con chocolate +Proteínas 1,3 g m.g 1...",Hacendado,Pack,4 ud. x 120 g,"1,75 €",Mercadona
1581,Natillas sabor vainilla +Proteínas 12 g prote...,Hacendado,Pack,4 ud. x 120 g,"1,75 €",Mercadona
1582,Pudding sabor caramelo +Proteínas 12 g proteínas,Hacendado,Pack,4 ud. x 120 g,"1,90 €",Mercadona
1583,Yogur azucarado YogoMix Discos con disquitos ...,Hacendado,Pack,2 ud. x 150 g,"1,20 €",Mercadona
1584,Copa de chocolate y nata +Proteínas 15 g prot...,Hacendado,Bote,150 g,"1,15 €",Mercadona

In [39]:
glyeb.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1585 entries, 0 to 1584
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   producto      1585 non-null   object
 1   marca         1585 non-null   object
 2   formato       1585 non-null   object
 3   cantidad      1585 non-null   object
 4   precio        1585 non-null   object
 5   supermercado  1585 non-null   object
dtypes: object(6)
memory usage: 696.2 KB

In [8]:
glyeb['formato'].value_counts()

Pack            390
Botella         175
Paquete         153
bolsa           151
bandeja         125
sobre           107
Caja             68
frasco           47
Bote             40
Tarrina          38
Brick            36
tarrina          35
Vaso             33
Bandeja          28
ud.              26
Lata             22
Botellín         22
caja             17
lata             10
Biberón          10
paquete           8
Pieza             8
vaso              7
Bol               6
Granel            4
blister           4
Pieza entera      4
pack              3
Garrafa           2
Benjamín          2
malla             1
Frasco            1
rulo              1
spbre             1
Name: formato, dtype: int64

In [9]:
glyeb['formato'] = glyeb['formato'].str.capitalize()

In [10]:
glyeb['formato']=glyeb['formato'].str.replace('spbre','Sobre')

In [11]:
glyeb['formato']=glyeb['formato'].str.replace('ud.','Paquete')

In [14]:
glyeb.to_csv('glyeb.csv', index=False)

In [15]:

archivos_csv = glob.glob('data/jose/*.csv')

# Crear una lista vacía para almacenar los datos de los archivos CSV
datos_csv = []

# Leer cada archivo CSV y agregar sus datos a la lista
for archivo in archivos_csv:
    datos = pd.read_csv(archivo)
    datos_csv.append(datos)

# Concatenar los datos de todos los archivos en un solo DataFrame
datos_combinados = pd.concat(datos_csv)

# Guardar los datos combinados en un nuevo archivo CSV
datos_combinados.to_csv('jose.csv', index=False)

In [16]:
jose = pd.read_csv('jose.csv')

In [17]:
jose

,producto,marca,formato,cantidad,precio,supermercado
0,Compresas ultrafinas normal con alas,Esos Dias,Bolsa,16 unidades,"1,49 €",Dia
1,Compresas ultrafinas super con alas,Esos Dias,Bolsa,14 unidades,"1,49 €",Dia
2,Protegeslips clásico,Esos Dias,Caja,40 unidades,"0,99 €",Dia
3,Protegeslips maxi,Esos Dias,Caja,36 unidades,"1,89 €",Dia
4,Tampón con aplicador compact súper,Esos Dias,Caja,32 unidades,"2,98 €",Dia
...,...,...,...,...,...,...
3454,Mascarilla reconstructora rizos definidos,Pantene,Frasco,300 ml,"4,29 €",Dia
3455,Aceite extraordinario,Elvive,Bote,100 ml,"9,99 €",Dia
3456,Serum intensivo repara y protege cabello dañado,Pantene,Spray,75 ml,"6,95 €",Dia
3457,Mascarilla capilar total repair,Elvive,Frasco,310 ml,"4,50 €",Dia
3458,Mascarilla capilar color vive,Elvive,Frasco,310 ml,"4,50 €",Dia

In [19]:
jose['formato'].value_counts()

Bolsa                    569
Caja                     430
Paquete                  404
Botella                  351
Bote                     326
Bandeja                  210
Spray                    192
Frasco                   176
Lata                     116
Tableta                  108
Pieza                    102
Tubo                      95
Blister                   77
Tarrina                   66
Tarro                     49
Brik                      26
Brick                     24
Sobre                     23
Garrafa                   23
Pack                      13
Palo                       9
Estropajo                  8
Bolsas                     8
Formato no encontrado      7
Bol                        5
Gel                        4
Estuche                    4
Para coche                 4
Electrico                  4
Stick                      2
Gofre                      2
Pastilla                   2
Cubo                       2
Recogedor                  2
Bolsitas                   2
Perlas                     2
Muñeco                     2
Sobres                     1
Escoba                     1
Velon                      1
Cepillo                    1
Plumero                    1
Bayeta                     1
Malla                      1
Vaso                       1
Bolsita                    1
Blíster                    1
Name: formato, dtype: int64

In [20]:
jose['formato']=jose['formato'].str.replace('Formato no encontrado','Paquete')

In [22]:
jose.to_csv('jose.csv', index=False)

In [23]:
archivos_csv = glob.glob('data/fer/*.csv')

# Crear una lista vacía para almacenar los datos de los archivos CSV
datos_csv = []

# Leer cada archivo CSV y agregar sus datos a la lista
for archivo in archivos_csv:
    datos = pd.read_csv(archivo)
    datos_csv.append(datos)

# Concatenar los datos de todos los archivos en un solo DataFrame
datos_combinados = pd.concat(datos_csv)

# Guardar los datos combinados en un nuevo archivo CSV
datos_combinados.to_csv('fer.csv', index=False)

In [10]:
fer = pd.read_csv('fer.csv')

In [11]:
fer

,producto,marca,formato,cantidad,precio,supermercado
0,Huevos frescos categoría A clase L,Huevos Garrido,Caja,12 unidades,"2,26 €",Dia
1,Huevos frescos categoría A clase M,Huevos Garrido,Caja,12 unidades,"2,02 €",Dia
2,Huevos frescos categoría A clase XL,Huevos Garrido,Caja,6 unidades,"1,69 €",Dia
3,Huevos frescos categoría A clase M,Huevos Garrido,Caja,24 unidades,"3,80 €",Dia
4,Huevos frescos categoría A clase L,Dia,Bandeja,12 unidades,"2,26 €",Dia
...,...,...,...,...,...,...
1844,Patatas fritas onduladas sabor a jamón,Ruffles,Bolsa,150 g,"1,99 €",Dia
1845,Nachos sabor a queso,Doritos,Bolsa,140 g,"1,99 €",Dia
1846,Nachips,Old El Paso,Bolsa,200 g,"2,75 €",Dia
1847,Patatas fritas al horno,Lay's,Bolsa,150 g,"2,49 €",Dia
1848,Aperitivo horneado con sabor a queso y ketchup,Cheetos,Bolsa,96 g,"1,99 €",Dia

In [31]:
fer['formato']=fer['formato'].fillna('Paquete')

In [24]:
archivos_csv = glob.glob('data/fran/*.csv')

# Crear una lista vacía para almacenar los datos de los archivos CSV
datos_csv = []

# Leer cada archivo CSV y agregar sus datos a la lista
for archivo in archivos_csv:
    datos = pd.read_csv(archivo)
    datos_csv.append(datos)

# Concatenar los datos de todos los archivos en un solo DataFrame
datos_combinados = pd.concat(datos_csv)

# Guardar los datos combinados en un nuevo archivo CSV
datos_combinados.to_csv('fran.csv', index=False)

In [25]:
fran = pd.read_csv('fran.csv')

In [26]:
fran

,producto,marca,formato,cantidad,precio,supermercado
0,Manzana golden,Dia,Bolsa,1 Kg,"1,99 €",Dia
1,Manzana roja,Dia,Bolsa,1 Kg,"2,19 €",Dia
2,Manzana pink lady,Dia,Bandeja,550 g,"1,99 €",Dia
3,Manzana golden,Dia,Granel,1 Kg,"2,19 €",Dia
4,Manzana granny,Dia,Granel,800 g,"1,75 €",Dia
...,...,...,...,...,...,...
1323,Licor de crema de cacao,La castellana,Botella,70 cl,"10,99 €",Dia
1324,Whisky Tennessee apple,Jack Daniel's,Botella,70 cl,"23,25 €",Dia
1325,Licor de ginebra,1902,Botella,70 cl,"7,99 €",Dia
1326,Licor de anís dulce,Chinchon,Botella,1 l,"11,99 €",Dia
1327,Licor de café,Abadía da Cova,Botella,70 cl,"10,35 €",Dia

In [27]:
fran['formato'].value_counts()

Botella      386
Caja         233
Paquete      135
Bolsa        121
Lata          94
Bandeja       76
Minipack      71
Pieza         44
Brick         43
Tarrina       18
Bote          16
Granel        14
Malla         13
Brik          12
frasco         9
Selección      6
Unidad         5
Spray          4
unidad         3
Tarro          3
Filetes        3
Bol            3
Vaso           2
Tubo           2
Pastilla       2
lote           1
Pack           1
Name: formato, dtype: int64

In [28]:
fran['formato'] = fran['formato'].str.capitalize()

In [29]:
fran.to_csv('fran.csv', index=False)

In [30]:


# Lista de archivos CSV
archivos_csv = ['fran.csv', 'jose.csv', 'fer.csv', 'carmen.csv', 'glyeb.csv']

# Crear un DataFrame vacío
df_final = pd.DataFrame()

# Leer y combinar los archivos CSV
for archivo in archivos_csv:
    df = pd.read_csv(archivo)
    df_final = pd.concat([df_final, df])

# Guardar el DataFrame combinado en un nuevo archivo CSV
df_final.to_csv('productos_supermercado.csv', index=False)

In [31]:
productos = pd.read_csv('productos_supermercado.csv')

In [32]:
productos

,producto,marca,formato,cantidad,precio,supermercado
0,Manzana golden,Dia,Bolsa,1 Kg,"1,99 €",Dia
1,Manzana roja,Dia,Bolsa,1 Kg,"2,19 €",Dia
2,Manzana pink lady,Dia,Bandeja,550 g,"1,99 €",Dia
3,Manzana golden,Dia,Granel,1 Kg,"2,19 €",Dia
4,Manzana granny,Dia,Granel,800 g,"1,75 €",Dia
...,...,...,...,...,...,...
10431,"Natillas con chocolate +Proteínas 1,3 g m.g 1...",Hacendado,Pack,4 ud. x 120 g,"1,75 €",Mercadona
10432,Natillas sabor vainilla +Proteínas 12 g prote...,Hacendado,Pack,4 ud. x 120 g,"1,75 €",Mercadona
10433,Pudding sabor caramelo +Proteínas 12 g proteínas,Hacendado,Pack,4 ud. x 120 g,"1,90 €",Mercadona
10434,Yogur azucarado YogoMix Discos con disquitos ...,Hacendado,Pack,2 ud. x 150 g,"1,20 €",Mercadona
10435,Copa de chocolate y nata +Proteínas 15 g prot...,Hacendado,Bote,150 g,"1,15 €",Mercadona

In [33]:
productos['precio'] = productos['precio'].str.replace(' €', '')

In [37]:
productos['formato'] = productos['formato'].str.capitalize()

In [40]:
productos['formato'].value_counts()

Botella         1292
Caja            1271
Paquete         1257
Bolsa           1253
Bote             964
Lata             622
Bandeja          561
Frasco           526
Pack             413
Brik             261
Spray            236
Tarrina          234
Pieza            197
Sobre            164
Tarro            159
Tableta          147
Tubo             129
Brick            122
Blister           81
Minipack          71
Vaso              66
Garrafa           46
Malla             45
Estuche           35
Ud.               26
Botellín          25
Tarrito           25
Bol               23
Unidad            22
Granel            19
Roll-on           15
Biberón           12
Palo               9
Estropajo          8
Bolsas             8
Saco               7
Selección          6
Stick              5
Pastilla           5
Vasito             4
Gel                4
Electrico          4
Para coche         4
Pieza entera       4
Filetes            3
Recogedor          2
Bolsitas           2
Benjamín           2
Manojo             2
Crema              2
Sobres             2
Cubo               2
Perlas             2
Muñeco             2
Gofre              2
Velon              1
 sobres            1
Escoba             1
Blíster            1
Polvo              1
Lote               1
Bolsita            1
Piedra             1
Bayeta             1
Plumero            1
Cepillo            1
Rulo               1
Spbre              1
En rulo            1
Name: formato, dtype: int64

In [42]:
productos['formato']=productos['formato'].str.replace('Spbre','Sobre')

In [43]:
productos['formato']=productos['formato'].str.replace(' sobres','Sobre')

In [44]:
productos['formato']=productos['formato'].str.replace('Ud.','Paquete')

In [46]:
productos['formato']=productos['formato'].fillna('Paquete')

In [47]:
productos.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10436 entries, 0 to 10435
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   producto      10436 non-null  object
 1   marca         10436 non-null  object
 2   formato       10436 non-null  object
 3   cantidad      10436 non-null  object
 4   precio        10436 non-null  object
 5   supermercado  10436 non-null  object
dtypes: object(6)
memory usage: 4.1 MB

In [51]:
productos['precio'] = productos['precio'].str.replace(',', '.')

In [53]:
productos['precio'] = productos['precio'].astype(float)

In [55]:
productos.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10436 entries, 0 to 10435
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   producto      10436 non-null  object
 1   marca         10436 non-null  object
 2   formato       10436 non-null  object
 3   cantidad      10436 non-null  object
 4   precio        10436 non-null  float64
 5   supermercado  10436 non-null  object
dtypes: float64(1), object(5)
memory usage: 3.6 MB

In [54]:
productos.to_csv('productos.csv', index=False)

In [6]:
productos=pd.read_csv('productos.csv')

In [6]:
productos

,producto,marca,formato,cantidad,precio,supermercado
0,Manzana golden,Dia,Bolsa,1 Kg,1.99,Dia
1,Manzana roja,Dia,Bolsa,1 Kg,2.19,Dia
2,Manzana pink lady,Dia,Bandeja,550 g,1.99,Dia
3,Manzana golden,Dia,Granel,1 Kg,2.19,Dia
4,Manzana granny,Dia,Granel,800 g,1.75,Dia
...,...,...,...,...,...,...
10431,"Natillas con chocolate +Proteínas 1,3 g m.g 1...",Hacendado,Pack,4 ud. x 120 g,1.75,Mercadona
10432,Natillas sabor vainilla +Proteínas 12 g prote...,Hacendado,Pack,4 ud. x 120 g,1.75,Mercadona
10433,Pudding sabor caramelo +Proteínas 12 g proteínas,Hacendado,Pack,4 ud. x 120 g,1.90,Mercadona
10434,Yogur azucarado YogoMix Discos con disquitos ...,Hacendado,Pack,2 ud. x 150 g,1.20,Mercadona
10435,Copa de chocolate y nata +Proteínas 15 g prot...,Hacendado,Bote,150 g,1.15,Mercadona

In [8]:
def categorizar_producto_final(producto):
    producto = producto.lower()
    if any(fruit in producto for fruit in ["manzana", "pera", "tomate", "zanahoria"]):
        return "Fruta y verdura"
    elif any(meat in producto for meat in ["pollo", "cerdo", "ternera", "carne"]):
        return "Carne"
    elif any(seafood in producto for seafood in ["pescado", "marisco", "salmón"]):
        return "Marisco y pescado"
    elif any(drink in producto for drink in ["agua", "refresco", "zumo"]):
        return "Agua y refrescos"
    elif any(bodega in producto for bodega in ["brandy", "vino", "cerveza", "whisky", "bebida espirituosa"]):
        return "Bodega"
    elif any(lacteo in producto for lacteo in ["leche", "yogur", "queso", "mantequilla", "huevo"]):
        return "Huevos, leche y mantequillla"
    else:
        return "Otro"


productos['categoría'] = productos['producto'].apply(categorizar_producto_final)

In [12]:
productos = productos.drop('categoría', axis=1)

In [13]:
productos.head()

            producto marca  formato cantidad  precio supermercado
0     Manzana golden   Dia    Bolsa     1 Kg    1.99          Dia
1       Manzana roja   Dia    Bolsa     1 Kg    2.19          Dia
2  Manzana pink lady   Dia  Bandeja    550 g    1.99          Dia
3     Manzana golden   Dia   Granel     1 Kg    2.19          Dia
4     Manzana granny   Dia   Granel    800 g    1.75          Dia

In [15]:
categoría = pd.read_csv('columna_categoria.csv')

In [54]:
categoría.value_counts()

Higiene                               2295
Leche y yogures                        741
Bebidas con alcohol                    699
Miel, caramelos y chocolate            665
Conservas, caldos y cremas             625
Congelados                             623
Charcutería y quesos                   561
Aceite, vinagre, especias y salsas     417
Panadería y pastelería                 404
Limpieza                               380
Cereales y galletas                    345
Fruta y verduras                       339
Pizzas y platos preparados             339
Refrescos                              333
Mascota                                274
Frutos secos                           273
Carne                                  273
Café e infusiones                      266
Arroz legumbres y pasta                199
Marisco y pescado                      127
Zumos                                  113
Agua                                    82
Mantequilla                             33
Huevos                                  24
Bebidas sin alcohol                      6
Name: categoria, dtype: int64

In [18]:
categoría = categoría['categoria'].str.capitalize()

In [21]:
categoría = categoría.str.replace('Infuciones','Infusiones')

In [23]:
categoría = categoría.str.replace('Cabrito','Carne')
categoría = categoría.str.replace('Cordero','Carne')
categoría = categoría.str.replace('Conejo','Carne')
categoría = categoría.str.replace('Pavo','Carne')
categoría = categoría.str.replace('Ternera','Carne')
categoría = categoría.str.replace('Pollo','Carne')
categoría = categoría.str.replace('Cerdo','Carne')

In [25]:
categoría = categoría.str.replace('Cordonices','Carne')

In [27]:
categoría = categoría.str.replace('Vino','Bebidas con alcohol')
categoría = categoría.str.replace('Cerveza','Bebidas con alcohol')

In [30]:
categoría = categoría.str.replace('Frutas','Fruta y verduras')
categoría = categoría.str.replace('Verduras','Fruta y verduras')

In [32]:
categoría = categoría.str.replace('Embutidos','Charcutería y quesos')
categoría = categoría.str.replace('Quesos','Charcutería y quesos')

In [34]:
categoría = categoría.str.replace('Helado','Congelados')

In [36]:
categoría = categoría.str.replace('Sal','Aceite, vinagre, especias y salsas')
categoría = categoría.str.replace('Azucar','Aceite, vinagre, especias y salsas')
categoría = categoría.str.replace('Aceite y vinagre','Aceite, vinagre, especias y salsas')
categoría = categoría.str.replace('Salsas','Aceite, vinagre, especias y salsas')

In [51]:
categoría = categoría.str.replace('Especias','Aceite, vinagre, especias y salsas')

In [38]:
categoría = categoría.str.replace('Cereales','Cereales y galletas')
categoría = categoría.str.replace('Galletas','Cereales y galletas')

In [40]:
categoría = categoría.str.replace('Miel','Miel, caramelos y chocolate')
categoría = categoría.str.replace('Chocolate y postres','Miel, caramelos y chocolate')
categoría = categoría.str.replace('Caramelos y golosinas','Miel ,caramelos y chocolate')

In [42]:
categoría = categoría.str.replace('Aceite, vinagre, especias y salsassas','Aceite, vinagre, especias y salsas')

In [44]:
categoría = categoría.str.replace('Bolleria','Panadería y pastelería')
categoría = categoría.str.replace('Pan','Panadería y pastelería')
categoría = categoría.str.replace('Harina','Panadería y pastelería')

In [46]:
categoría = categoría.str.replace('Panadería y pasteleríaadería y pastelería','Panadería y pastelería')

In [48]:
categoría = categoría.str.replace('Conservas','Conservas, caldos y cremas')
categoría = categoría.str.replace('Gazpachos y salmorejos','Conservas, caldos y cremas')

In [50]:
categoría = categoría.str.replace('Mariscos y pescados','Marisco y pescado')
categoría = categoría.str.replace('Sushi','Marisco y pescado')

In [53]:
categoría = categoría.str.replace('Cafe','Café e infusiones')
categoría = categoría.str.replace('Infusiones','Café e infusiones')
categoría = categoría.str.replace('Miel ,caramelos y chocolate','Miel, caramelos y chocolate')

In [56]:
productos = productos.merge(categoría, left_index=True, right_index=True)

In [58]:
productos = productos.rename(columns={'categoria': 'categoría'})

In [62]:
categoría.unique( )

array(['Fruta y verduras', 'Bebidas con alcohol', 'Huevos',
       'Conservas, caldos y cremas', 'Cereales y galletas',
       'Marisco y pescado', 'Congelados', 'Bebidas sin alcohol',
       'Leche y yogures', 'Higiene', 'Frutos secos', 'Zumos',
       'Pizzas y platos preparados', 'Panadería y pastelería',
       'Mantequilla', 'Limpieza', 'Miel, caramelos y chocolate',
       'Charcutería y quesos', 'Carne', 'Mascota',
       'Aceite, vinagre, especias y salsas', 'Refrescos',
       'Arroz legumbres y pasta', 'Café e infusiones', 'Agua'],
      dtype=object)

In [59]:
productos.head()

,producto,marca,formato,cantidad,precio,supermercado,categoría
0,Manzana golden,Dia,Bolsa,1 Kg,1.99,Dia,Fruta y verduras
1,Manzana roja,Dia,Bolsa,1 Kg,2.19,Dia,Fruta y verduras
2,Manzana pink lady,Dia,Bandeja,550 g,1.99,Dia,Fruta y verduras
3,Manzana golden,Dia,Granel,1 Kg,2.19,Dia,Fruta y verduras
4,Manzana granny,Dia,Granel,800 g,1.75,Dia,Fruta y verduras

In [ ]:
productos['id_producto'] = productos.index+1

In [60]:
productos.to_csv('productos_categoría.csv', index=False)